export default {
  /******* Used for Login and Logout, Users*******/
  USER_LOGOUT: "USER_LOGOUT",

  /* used for add category */
  ADD_CATEGORY: "ADD_CATEGORY",
  CATEGORY_LISTING: "CATEGORY_LISTING",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  /* used for add expense */
  ADD_EXPENSE: "ADD_EXPENSE",
  EXPENSE_LISTING: "EXPENSE_LISTING",
  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  EXPENSE_CATEGORY_LISTING: "EXPENSE_CATEGORY_LISTING",
  CATEGORY_LIST_LOADING: "CATEGORY_LIST_LOADING",

  /* used for both category and expense display */
  EXPENSE_CATEGORY_DISPLAY: "EXPENSE_CATEGORY_DISPLAY",
};
